JSON_AS_ASCII = false
APPLICATION_ROOT = "/"
PREFERRED_URL_SCHEME = "https"
JSON_SORT_KEYS = false
CACHE_TYPE = "filesystem"
CACHE_DIR = "./cache"
CACHE_DEFAULT_TIMEOUT = 300
CACHE_IGNORE_ERRORS = true
