JSON_AS_ASCII = false
APPLICATION_ROOT = "/"
PREFERRED_URL_SCHEME = "https"
JSON_SORT_KEYS = false
CACHE_TYPE = "simple"
CACHE_DIR = "./cache"
CACHE_DEFAULT_TIMEOUT = 300
CACHE_IGNORE_ERRORS = true

SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite3"
SQLALCHEMY_TRACK_MODIFICATIONS = false
